package compile

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/aoiflux/fsagen/email"
	"github.com/aoiflux/fsagen/render"
	"github.com/aoiflux/fsagen/spec"
)

// getTemplate returns a predefined content template. The name has already
// been checked against Templates.
func getTemplate(templateName string, ctx render.Context) (string, error) {
	switch templateName {
	case "email":
		// Built by the same code as action: email, so the message has CRLF
		// line endings, a Message-ID and MIME headers, and net/mail reads it.
		// It used to be a hand-written imitation with none of those.
		key := ctx.Rand.Derive("template", "email")
		from := strings.ToLower(ctx.Actor)
		if from == "" {
			from = "user"
		}
		msg, _, err := email.Build(email.Options{
			Spec: spec.EmailSpec{
				From:      from + "@example.com",
				To:        []string{"recipient@example.com"},
				Subject:   key.Derive("subject").Stream().Text(20),
				Date:      ctx.Timestamp.UTC().Format(time.RFC3339),
				MessageID: "<" + key.Derive("message-id").Stream().Hex(24) + "@example.com>",
				BodyText:  fmt.Sprintf("This is an automated message from %s.\n\nMessage ID: %d\n", ctx.Actor, ctx.Seq),
			},
			Boundary: func() string { return "----=_fsagen_" + key.Derive("boundary").Stream().Hex(24) },
		})
		if err != nil {
			return "", err
		}
		return string(msg), nil

	case "log":
		return fmt.Sprintf(`%s [INFO] User=%s Action=file_access File=document_%d.txt Result=success
%s [WARN] User=%s Action=failed_login Attempts=3
%s [INFO] User=%s Action=logout SessionID=%d
`,
			ctx.Timestamp.Format(time.RFC3339),
			ctx.Actor,
			ctx.Seq,
			ctx.Timestamp.Add(1*time.Minute).Format(time.RFC3339),
			ctx.Actor,
			ctx.Timestamp.Add(2*time.Minute).Format(time.RFC3339),
			ctx.Actor,
			ctx.Seq), nil

	case "script":
		return fmt.Sprintf(`#!/bin/bash
# Generated by %s at %s
# Sequence: %d

echo "Running automated task"
echo "User: %s"
echo "Timestamp: %s"
`,
			ctx.Actor,
			ctx.Timestamp.Format(time.RFC3339),
			ctx.Seq,
			ctx.Actor,
			ctx.Timestamp.Format(time.RFC3339)), nil

	case "doc":
		return fmt.Sprintf(`Document Title: Report %d
Author: %s
Date: %s

This is a generated document for testing purposes.
Document ID: %d
Generated content: %s
`,
			ctx.Seq,
			ctx.Actor,
			ctx.Timestamp.Format("2006-01-02"),
			ctx.Seq,
			ctx.Rand.Derive("template", "doc", "body").Stream().Text(100)), nil
	}
	panic("unchecked template " + templateName)
}

func parseDurationSafe(s string) (time.Duration, error) {
	if strings.TrimSpace(s) == "" {
		return 0, nil
	}
	return parseDuration(s)
}

var reDayWeek = regexp.MustCompile(`^(\d+)([dw])`)

// parseDuration extends time.ParseDuration with day and week units. Scenarios
// here run over days ("2d6h" for a 54-hour dwell time), and Go's parser stops
// at hours.
func parseDuration(s string) (time.Duration, error) {
	s = strings.TrimSpace(s)
	var total time.Duration
	sawUnit := false

	for {
		m := reDayWeek.FindStringSubmatch(s)
		if m == nil {
			break
		}
		n, err := strconv.Atoi(m[1])
		if err != nil {
			return 0, fmt.Errorf("invalid duration %q: %w", s, err)
		}
		unit := 24 * time.Hour
		if m[2] == "w" {
			unit = 7 * 24 * time.Hour
		}
		total += time.Duration(n) * unit
		sawUnit = true
		s = s[len(m[0]):]
	}

	if s == "" {
		if !sawUnit {
			return 0, fmt.Errorf("invalid duration: empty")
		}
		return total, nil
	}

	rest, err := time.ParseDuration(s)
	if err != nil {
		return 0, err
	}
	return total + rest, nil
}
