package prng

import (
	"strings"
	"testing"
)

// TestPRNGGoldenVectors pins the scheme: key derivation, ChaCha8 and every
// value mapping. If it fails, every generated byte has changed, which needs
// a new scheme name and a new generator version, not an edit here.
func TestPRNGGoldenVectors(t *testing.T) {
	k := Root(42)
	if got := k.String(); got != "924cdf4c47306a2f" {
		t.Errorf("Root(42) = %s", got)
	}
	s := k.Derive("op", "x").Stream()
	if got := s.Uint64(); got != 10076606334720310485 {
		t.Errorf("Uint64 = %d", got)
	}
	if got := s.IntN(1000); got != 980 {
		t.Errorf("IntN = %d", got)
	}
	if got := s.Text(16); got != "PV35EV67L4FVKJEJ" {
		t.Errorf("Text = %s", got)
	}
	if got := s.Hex(16); got != "889ad7fac21de356" {
		t.Errorf("Hex = %s", got)
	}
	if got := s.UUID(); got != "b6d80e18-c2f4-43dd-a19e-d3e27cdcc0d9" {
		t.Errorf("UUID = %s", got)
	}
	if got := Root(-1).Derive("a", "bc").Stream().Bytes(12); string(got) != "\xb0\x02\x05\x08\xb2\x74\x72\x27\x35\x18\x86\x94" {
		t.Errorf("Bytes = %x", got)
	}
}

func TestDeriveSeparatesParts(t *testing.T) {
	r := Root(1)
	if r.Derive("ab", "c") == r.Derive("a", "bc") {
		t.Error("parts are not length-prefixed")
	}
	if r.Derive("a") == Root(2).Derive("a") {
		t.Error("the seed does not reach derived keys")
	}
	if r.Derive("a").Stream().Text(32) != r.Derive("a").Stream().Text(32) {
		t.Error("the same key gave two different streams")
	}
}

func TestValueShapes(t *testing.T) {
	s := Root(3).Stream()
	for i := 0; i < 2000; i++ {
		if n := s.IntN(7); n < 0 || n >= 7 {
			t.Fatalf("IntN(7) = %d", n)
		}
	}
	if h := s.Hex(100); len(h) != 100 || strings.Trim(h, "0123456789abcdef") != "" {
		t.Errorf("Hex = %q", h)
	}
	if x := s.Text(100); len(x) != 100 || strings.Trim(x, textAlphabet) != "" {
		t.Errorf("Text = %q", x)
	}
	for i := 0; i < 50; i++ {
		u := s.UUID()
		parts := strings.Split(u, "-")
		if len(parts) != 5 || len(parts[0]) != 8 || len(parts[4]) != 12 || parts[2][0] != '4' || !strings.ContainsRune("89ab", rune(parts[3][0])) {
			t.Fatalf("malformed UUID %q", u)
		}
	}
	if len(s.Bytes(13)) != 13 || s.Bytes(0) != nil {
		t.Error("Bytes length")
	}
}
