// Package prng provides the keyed random streams every generated value is
// drawn from.
//
// There is no global generator. Each consumer derives its own key from the
// run's root key and a path of names (the operation's identity, the field,
// the token), and draws from a ChaCha8 stream seeded with that key. So a
// value depends only on the seed and its own name: adding, removing or
// reordering an unrelated operation, field or token never changes it.
//
// The mapping from stream output to values (text, hex, integers in a range,
// UUIDs) is defined here rather than taken from math/rand, whose derived
// methods are not promised to stay stable across Go releases. ChaCha8's own
// output is fixed by its specification (c2sp.org/chacha8rand).
package prng

import (
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"math"
	"math/rand/v2"
	"strconv"
)

// Scheme names this key-derivation and value-mapping scheme. Changing
// anything in this file changes every generated byte; that needs a new
// scheme name and a new generator version.
const Scheme = "fsagen-chacha8-1"

// Key identifies one stream.
type Key [32]byte

// Root is the key for a run with the given seed.
func Root(seed int64) Key {
	h := sha256.New()
	writePart(h, Scheme)
	writePart(h, strconv.FormatInt(seed, 10))
	var k Key
	h.Sum(k[:0])
	return k
}

// Derive returns the key for the named child of k. Parts are length-prefixed,
// so ("ab", "c") and ("a", "bc") name different children.
func (k Key) Derive(parts ...string) Key {
	h := sha256.New()
	h.Write(k[:])
	for _, p := range parts {
		writePart(h, p)
	}
	var out Key
	h.Sum(out[:0])
	return out
}

// Stream starts a new stream for k. Two streams from the same key produce
// the same values.
func (k Key) Stream() *Stream { return &Stream{c: rand.NewChaCha8(k)} }

// String shows a key in logs and test failures.
func (k Key) String() string { return fmt.Sprintf("%x", k[:8]) }

type hashWriter interface{ Write([]byte) (int, error) }

func writePart(h hashWriter, s string) {
	var n [8]byte
	binary.BigEndian.PutUint64(n[:], uint64(len(s)))
	h.Write(n[:])
	h.Write([]byte(s))
}

// Stream is a sequence of random values. It is not safe for concurrent use;
// give each goroutine its own key instead.
type Stream struct {
	c *rand.ChaCha8
}

// Uint64 returns the next 64 bits of the stream.
func (s *Stream) Uint64() uint64 { return s.c.Uint64() }

// IntN returns a uniform integer in [0, n), by rejection sampling. It panics
// if n <= 0.
func (s *Stream) IntN(n int) int {
	if n <= 0 {
		panic("prng: IntN of a non-positive bound")
	}
	un := uint64(n)
	// rem is 2^64 mod n; the top rem values of the range would bias the
	// result, so they are drawn again.
	rem := (math.MaxUint64%un + 1) % un
	for {
		v := s.Uint64()
		if rem == 0 || v <= math.MaxUint64-rem {
			return int(v % un)
		}
	}
}

// Bytes returns n bytes: each Uint64, little-endian, in turn. The unused
// bytes of the last word are discarded.
func (s *Stream) Bytes(n int) []byte {
	if n <= 0 {
		return nil
	}
	out := make([]byte, n)
	var w [8]byte
	for i := 0; i < n; i += 8 {
		binary.LittleEndian.PutUint64(w[:], s.Uint64())
		copy(out[i:], w[:])
	}
	return out
}

// textAlphabet is RFC 4648 base32's alphabet, which is what fsagen's random
// text has always looked like.
const textAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"

// Text returns n characters from the base32 alphabet, one per byte (the low
// five bits, which are uniform).
func (s *Stream) Text(n int) string {
	b := s.Bytes(n)
	for i := range b {
		b[i] = textAlphabet[b[i]&31]
	}
	return string(b)
}

// Hex returns n lowercase hex digits, one per byte (the low four bits).
func (s *Stream) Hex(n int) string {
	const digits = "0123456789abcdef"
	b := s.Bytes(n)
	for i := range b {
		b[i] = digits[b[i]&15]
	}
	return string(b)
}

// UUID returns a well-formed RFC 4122 version 4 UUID.
func (s *Stream) UUID() string {
	b := s.Bytes(16)
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}
